export enum AuthActionEnum{
    LOGIN_EMAIL_REQUEST = 'LOGIN_EMAIL_REQUEST',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    SET_TOKEN = 'SET_TOKEN',
    LOGIN_FAILED = 'LOGIN_FAILED',
    LOGOUT = 'LOGOUT',
}