export enum ChatActionsEnum{
    SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST",
    SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS",
    SEND_MESSAGE_FAILED = "SEND_MESSAGE_FAILED",
    CLEAR_STATE = "CLEAR_STATE"
}