export enum ChatActionsEnum {
    SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST",
    SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS",
    SEND_MESSAGE_FAILED = "SEND_MESSAGE_FAILED",
    CLEAR_UNRECEIVED_MESSAGE_STATE = "CLEAR_UNRECEIVED_MESSAGE_STATE"
}