export enum UserActionsEnum{
    PUT_USER_REQUEST = 'PUT_USER_REQUEST',
    PUT_USER_SUCCESS = 'PUT_USER_SUCCESS',
    PUT_USER_FAILED = 'PUT_USER_FAILED',
    PROFILE_LOGOUT_CLEAR_IMAGE = 'PROFILE_LOGOUT_CLEAR_IMAGE',
    PROFILE_IMAGE_CHANGED = 'PROFILE_IMAGE_CHANGED',
}